# -*- coding: utf-8 -*-
"""Predicting Diamonds Prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15r0YjyaDT1pqpJnhZmrItDJhllxbmbb-

### **by Hafizah Ab Rahim**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
mpl.rcParams['figure.dpi'] = 400

from google.colab import drive
drive.mount("/content/drive")
df = pd.read_csv("/content/drive/My Drive/Udacity/diamonds.csv")
df1 = pd.read_csv("/content/drive/My Drive/Udacity/new-diamonds.csv")

df.head(5)

fig, ax = plt.subplots()
ax.scatter(df["carat"], df["price"], color = "g", marker = ".")
ax.set_xlabel("carat")
ax.set_ylabel("price($)")
ax.set_title("Carat vs Price of Diamonds")
plt.show()

from sklearn.linear_model import LinearRegression
x = df[['carat','cut_ord', 'clarity_ord']]
y = df.price
lm1 = LinearRegression()
lm1.fit(x,y)
print(lm1.intercept_)
print(lm1.coef_)

list(zip(['carat', 'cut', 'clarity'],lm1.coef_))

df1.head(5)

x_test = df1[['carat','cut_ord', 'clarity_ord']]
pred = lm1.predict(x_test)
pred

df1['pred_price']= pred
df1.head(10)

fig, ax = plt.subplots()
ax.scatter(df1["carat"], df1["pred_price"], color = "r", marker = ".")
ax.set_xlabel("carat")
ax.set_ylabel("predicted_price($)")
ax.set_title("Carat vs Predicted_Price of Diamonds")
plt.show()

sum_= df1['pred_price'].sum()
sum_

margin_=0.7*sum_
margin_

plt.style.use("seaborn-dark-palette")
fig, ax = plt.subplots()
ax.scatter(df["carat"], df["price"], marker = ".", label="price")
ax.scatter(df1["carat"], df1["pred_price"], color = "r", marker = ".", label="predicted_price")
ax.set_xlabel("carat")
ax.set_ylabel("price($)")
ax.set_title("Carat vs Price of Diamonds")
ax.legend()
plt.show()